[package]
name = "physarum"
version = "0.1.0"
edition = "2018"

[dependencies]
wgpu = "*"
nanorand = "*"
winit = "*"
log = "*"
async-executor = "*"
env_logger = "*"
pollster = "*"
bytemuck = "*"
image = "*"
chrono = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"