[package]
name = "physarum"
version = "0.1.0"
edition = "2021"

[lib]
name = "physarum"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "physarum"
path = "src/main.rs"

[dependencies]
wgpu = "0.17.2"
getrandom = { version = "0.2", features = ["js"] }
rand = "*"
winit = "*"
log = "*"
async-executor = "*"
env_logger = "*"
pollster = "*"
bytemuck = "*"
image = "*"
chrono = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web-time = "0.2.3"

[dependencies.web-sys]
version = "0.3.65"
features = ["Location", "Window"]


[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.5"
wasm-bindgen-futures = "*"
wasm-bindgen = "*"
console_log = { version = "0.2" }
js-sys = "*"
